---
title: "02-Deseq-temperature"
output: html_document
---

```{r}
library(DESeq2)
```



```{r}
tmdf <- read.table("../data/kallisto-0517.isoform.counts.txt", header = T, sep = "\t")
rownames(tmdf) <- tmdf$FeatureID
tmdf <- tmdf[,-1]
head(tmdf)
```




```{r}
deseq2.colData <- data.frame(condition=factor(c(rep("Cold", 2), rep("Warm", 2))), 
                             type=factor(rep("paired-end", 4)))
rownames(deseq2.colData) <- colnames(data)
deseq2.dds <- DESeqDataSetFromMatrix(countData = tmdf,
                                     colData = deseq2.colData, 
                                     design = ~ condition)
```




```{r}
deseq2.dds <- DESeq(deseq2.dds)
deseq2.res <- results(deseq2.dds)
deseq2.res <- deseq2.res[order(rownames(deseq2.res)), ]
```


```{r}
head(deseq2.res)
```



```{r}
write.table(deseq2.res, "../analyses/deseq2.res-temp.tab", sep = "\t", row.names = T, quote = FALSE, col.names = TRUE)
```


```{r}
# Count number of hits with adjusted p-value less then 0.05
dim(deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ])

```




```{r}
tmp <- deseq2.res
# The main plot
plot(tmp$baseMean, tmp$log2FoldChange, pch=20, cex=0.45, ylim=c(-15, 15), log="x", col="darkgray",
     #main="Infection Status  (pval </= 0.05)",
     xlab="mean of normalized counts",
     ylab="Log2 Fold Change")
# Getting the significant points and plotting them again so they're a different color
tmp.sig <- deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ]
points(tmp.sig$baseMean, tmp.sig$log2FoldChange, pch=20, cex=0.45, col="red")
# 2 FC lines
abline(h=c(-1,1), col="blue")
```





```{r}
write.table(tmp.sig, "../analyses/DEG-temperature.tab", row.names = T, quote = FALSE, sep = '\t')

```


```{bash}
head ../analyses/DEG-temperature.tab
```

```{bash}
wc -l ../analyses/DEG-temperature.tab
```

#Make heatmap of top 20 
```{r}
library(pheatmap)
```

```{r}
#transform data 
vsd <- varianceStabilizingTransformation(deseq2.dds, blind = FALSE)#variance stabilizing transoformation
rld <- rlog(deseq2.dds, blind = FALSE) #controls for rows with few counts
ntd <- normTransform(deseq2.dds) #transforms data for plotting
top20 <- order(rowMeans(counts(deseq2.dds, normalized = TRUE)),
               decreasing = TRUE)[1:20] #average counts for each gene and select top 20 most abundant genes
pheatmap(assay(ntd)[top20,])
```


Try with blind=TRUE
```{r}
#transform data 
vsd <- varianceStabilizingTransformation(deseq2.dds, blind = TRUE)#variance stabilizing transoformation
rld <- rlog(deseq2.dds, blind = TRUE) #controls for rows with few counts
ntd <- normTransform(deseq2.dds) #transforms data for plotting
top20 <- order(rowMeans(counts(deseq2.dds, normalized = TRUE)),
               decreasing = TRUE)[1:20] #average counts for each gene and select top 20 most abundant genes
pheatmap(assay(ntd)[top20,])
```

Looks the same... 


```{r}
head(ntd)
```





