---
title: "heatmap-cluster-golists-for-revigo"
output: html_document
---
Rmd to get list of GO terms from each annotated list of genes in the 4 clusters of the heatmap. Heatmap is infection degs in Crabs C and E at time 2 and 17. 


```{r}
library(tidyverse)
library(dplyr)
```

### Crab C at day 2:
```{r}
crabC2_go <- read.delim("../analyses/crabC2_clustgenes_GO.tab", sep = '\t')
head(crabC2_go)
```

Print GO IDs:
```{r}
crab2_goIDS <- crabC2_go$gene_ontology_IDs
head(crab2_goIDS)
```

write out
```{r}
write.table(crab2_goIDS, "../analyses/crab2GOIDs.tab", sep = '\t', row.names = FALSE, quote = FALSE)
```

### Crab C at day 17:
```{r}
crabC17_go <- read.delim("../analyses/crabC17_clustgenes_GO.tab", sep = '\t')
head(crabC17_go)
```

Print GO IDs:
```{r}
crab17_goIDS <- crabC17_go$gene_ontology_IDs
head(crab17_goIDS)
```

write out
```{r}
write.table(crab17_goIDS, "../analyses/crab17GOIDs.tab", sep = '\t', row.names = FALSE, quote = FALSE)
```

### Crab E at day 2:
```{r}
crabE2_go <- read.delim("../analyses/crabE2_clustgenes_GO.tab", sep = '\t')
head(crabE2_go)
```

Print GO IDs:
```{r}
crabE2_goIDS <- crabE2_go$gene_ontology_IDs
head(crabE2_goIDS)
```

write out
```{r}
write.table(crabE2_goIDS, "../analyses/crabE2GOIDs.tab", sep = '\t', row.names = FALSE, quote = FALSE)
```


### Crab E at day 17:
```{r}
crabE17_go <- read.delim("../analyses/crabE17_clustgenes_GO.tab", sep = '\t')
head(crabE17_go)
```

Print GO IDs:
```{r}
crabE17_goIDS <- crabE17_go$gene_ontology_IDs
head(crabE17_goIDS)
```

write out
```{r}
write.table(crabE17_goIDS, "../analyses/crabE17GOIDs.tab", sep = '\t', row.names = FALSE, quote = FALSE)
```





